kubriXIngressDomain: "local" # gets overwritten by kubriX cluster appset
replicaCount: 1

image:
  repository: hashicorp/http-echo
  tag: "0.2.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# Message shown by the echo server
message: "Hello World from Helm!"

ingress:
  enabled: true
  className: "nginx-tietoevry"
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: hello-world.{{ .Values.kubriXIngressDomain }}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - hello-world.{{ .Values.kubriXIngressDomain }}
      secretName: hello-world-server-tls
